In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("C:\\Users\\NeelachalMohanty\\OneDrive - GyanSys Inc\\Desktop\\GENAI Assign\\CSV_BOT\\data\\StudentsPerformance.csv")

df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [12]:
df.nunique()

gender                          2
race/ethnicity                  5
parental level of education     6
lunch                           2
test preparation course         2
math score                     81
reading score                  72
writing score                  77
dtype: int64

In [4]:
df['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [5]:
df.nlargest(10, 'reading score')

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
106,female,group D,master's degree,standard,none,87,100,100
114,female,group E,bachelor's degree,standard,completed,99,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93
165,female,group C,bachelor's degree,standard,completed,96,100,100
179,female,group D,some high school,standard,completed,97,100,100
381,male,group C,associate's degree,standard,completed,87,100,95
458,female,group E,bachelor's degree,standard,none,100,100,100
546,female,group A,some high school,standard,completed,92,100,97
566,female,group E,bachelor's degree,free/reduced,completed,92,100,100
594,female,group C,bachelor's degree,standard,completed,92,100,99

In [14]:
df.query("gender == 'male' and (`math score` < 30 or `math score` > 70)")[['reading score', 'writing score']]

     reading score  writing score
4               78             75
13              72             70
16              89             86
24              71             80
25              74             72
..             ...            ...
971             72             69
981             78             78
982             85             86
987             75             76
990             81             75

[223 rows x 2 columns]